import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Roboto } from "next/font/google";
import Sidebar from "@/components/Sidebar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} liquid-glass relative antialiased`}>
        <div className="absolute top-0 left-0 bottom-0 z-10">
          <Sidebar />
        </div>
        {children}
      </body>
    </html>
  );
}

