import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import ControlPanel from "@/components/ControlPanel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${roboto.className} liquid-glass relative antialiased overflow-hidden`}
      >
        <aside className="absolute top-0 left-0 bottom-0 z-10">
          <Sidebar />
        </aside>
        {children}
        <aside className="absolute top-0 right-0 bottom-0 z-10">
          <ControlPanel />
        </aside>
      </body>
    </html>
  );
}

